### PR TITLE
Wait for release metadata to be flushed

### PR DESCRIPTION
**Pull request by jglick**
https://github.com/jenkins-infra/github-reusable-workflows/pull/1#issuecomment-1135852603

### CODE REVIEW

**Comment by jglick** [comment]
Seems to work https://github.com/jenkinsci/jenkins-infra-test-plugin/releases/tag/62.v0d4f02c3969f or maybe it was just working again by accident anyway.

Alternately, https://github.com/jenkinsci/jenkins-infra-test-plugin/runs/6716516319?check_suite_focus=true#step:3:77 I guess we could try to read the `body` output from Release Drafter. Would require changes to the interesting changes action; and I am not sure that would improve correctness in corner cases like when backport branches are in use.

**Comment by jetersen** [comment]
https://github.com/jenkins-infra/interesting-category-action/pull/5

Should be able to use it as well
```yaml
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        id: draft
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check interesting categories
        uses: jetersen/interesting-category-action@patch-1
        id: interesting-categories
        if: steps.verify-ci-status.outputs.result == 'success'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_DRAFT_BODY: ${{ steps.draft.outputs.body }}  
```

**Comment by jglick** [comment]
Do you care to prepare a branch of the workflow picking up your action patch and piping the output of the R.D. action to it? Then we can test it in an amendment to https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/21.

**Comment by jglick** [comment]
Prefer #3.

**Pull request closed without merging**
